# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apscesiDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_apscDialog(object):
    def setupUi(self, apscDialog):
        apscDialog.setObjectName("apscDialog")
        apscDialog.resize(400, 300)
        self.apscDialogText = QtWidgets.QPlainTextEdit(apscDialog)
        self.apscDialogText.setGeometry(QtCore.QRect(10, 20, 381, 251))
        self.apscDialogText.setObjectName("apscDialogText")
        self.aspcOKButton = QtWidgets.QPushButton(apscDialog)
        self.aspcOKButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.aspcOKButton.setObjectName("aspcOKButton")
        self.label_2 = QtWidgets.QLabel(apscDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(apscDialog)
        QtCore.QMetaObject.connectSlotsByName(apscDialog)

    def retranslateUi(self, apscDialog):
        _translate = QtCore.QCoreApplication.translate
        apscDialog.setWindowTitle(_translate("apscDialog", "Ostali apscesi"))
        self.aspcOKButton.setText(_translate("apscDialog", "OK"))
        self.label_2.setText(_translate("apscDialog", "Druge apscese upisati uredno ovde!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    apscDialog = QtWidgets.QDialog()
    ui = Ui_apscDialog()
    ui.setupUi(apscDialog)
    apscDialog.show()
    sys.exit(app.exec_())
