# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './KlinickiCentarHelper/lokalizacijaDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Dialog(object):
    drugeLok = ''
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lokDialogText = QtWidgets.QPlainTextEdit(Dialog)
        self.lokDialogText.setGeometry(QtCore.QRect(10, 20, 381, 251))
        self.lokDialogText.setObjectName("lokDialogText")
        self.lokOKButton = QtWidgets.QPushButton(Dialog)
        self.lokOKButton.setGeometry(QtCore.QRect(170, 270, 75, 23))
        self.lokOKButton.setObjectName("lokOKButton")

        self.lokZatButton = QtWidgets.QPushButton(Dialog)
        self.lokZatButton.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.lokZatButton.setObjectName(u"lokZatButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.lokOKButton.clicked.connect(self.takeText)
        self.lokZatButton.clicked.connect(Dialog.close)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Druge lokalizacije upisati uredno ovde!"))
        self.lokOKButton.setText(_translate("Dialog", "OK"))
        self.lokZatButton.setText(QCoreApplication.translate("Dialog", u"Zatvori!", None))
    
    def takeText(self):
        self.drugeLok = self.lokDialogText.toPlainText()
        print(self.drugeLok)
        self.lokOKButton.setEnabled(False)

        


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
