# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operacijeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_operacijeDialog(object):
    opis_Operacije = ''
    def setupUi(self, operacijeDialog):
        operacijeDialog.setObjectName("operacijeDialog")
        operacijeDialog.resize(400, 300)
        self.opDialogText = QtWidgets.QPlainTextEdit(operacijeDialog)
        self.opDialogText.setGeometry(QtCore.QRect(10, 20, 381, 251))
        self.opDialogText.setObjectName("opDialogText")
        self.rtgOKButton = QtWidgets.QPushButton(operacijeDialog)
        self.rtgOKButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.rtgOKButton.setObjectName("rtgOKButton")
        self.opIzlaz = QtWidgets.QPushButton(operacijeDialog)
        self.opIzlaz.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.opIzlaz.setObjectName("opIzlaz")
        self.label_2 = QtWidgets.QLabel(operacijeDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(operacijeDialog)
        QtCore.QMetaObject.connectSlotsByName(operacijeDialog)
        self.rtgOKButton.clicked.connect(self.getText)
        self.opIzlaz.clicked.connect(operacijeDialog.close)

    def retranslateUi(self, operacijeDialog):
        _translate = QtCore.QCoreApplication.translate
        operacijeDialog.setWindowTitle(_translate("operacijeDialog", "Operacije"))
        self.rtgOKButton.setText(_translate("operacijeDialog", "OK"))
        self.opIzlaz.setText(_translate("operacijeDialog", "Izlaz!"))
        self.label_2.setText(_translate("operacijeDialog", "Opis dati ovde!"))
    def getText(self):
        self.opis_Operacije = self.opDialogText.toPlainText()
        self.rtgOKButton.setEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    operacijeDialog = QtWidgets.QDialog()
    ui = Ui_operacijeDialog()
    ui.setupUi(operacijeDialog)
    operacijeDialog.show()
    sys.exit(app.exec_())
