# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'razloziOpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RazlogOpDialog(object):
    opis_RazOperacije = ''
    def setupUi(self, RazlogOpDialog):
        RazlogOpDialog.setObjectName("RazlogOpDialog")
        RazlogOpDialog.resize(400, 300)
        self.razlogOpDialogText = QtWidgets.QPlainTextEdit(RazlogOpDialog)
        self.razlogOpDialogText.setGeometry(QtCore.QRect(10, 20, 381, 251))
        self.razlogOpDialogText.setObjectName("razlogOpDialogText")
        self.razlogOpOKButton = QtWidgets.QPushButton(RazlogOpDialog)
        self.razlogOpOKButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.razlogOpOKButton.setObjectName("razlogOpOKButton")
        self.razlogOpIzlaz = QtWidgets.QPushButton(RazlogOpDialog)
        self.razlogOpIzlaz.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.razlogOpIzlaz.setObjectName("razlogOpIzlaz")
        self.label_2 = QtWidgets.QLabel(RazlogOpDialog)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(RazlogOpDialog)
        QtCore.QMetaObject.connectSlotsByName(RazlogOpDialog)
        self.razlogOpOKButton.clicked.connect(self.getText)
        self.razlogOpIzlaz.clicked.connect(RazlogOpDialog.close)

    def retranslateUi(self, RazlogOpDialog):
        _translate = QtCore.QCoreApplication.translate
        RazlogOpDialog.setWindowTitle(_translate("RazlogOpDialog", "Razlozi Operacija"))
        self.razlogOpOKButton.setText(_translate("RazlogOpDialog", "OK"))
        self.razlogOpIzlaz.setText(_translate("RazlogOpDialog", "Izlaz!"))
        self.label_2.setText(_translate("RazlogOpDialog", "Opis dati ovde!"))
    def getText(self):
        self.opis_RazOperacije = self.razlogOpDialogText.toPlainText()
        self.razlogOpOKButton.setEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RazlogOpDialog = QtWidgets.QDialog()
    ui = Ui_RazlogOpDialog()
    ui.setupUi(RazlogOpDialog)
    RazlogOpDialog.show()
    sys.exit(app.exec_())
