# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rtgDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RTGNalaz(object):
    rtg_Nalaz = ''
    def setupUi(self, RTGNalaz):
        RTGNalaz.setObjectName("RTGNalaz")
        RTGNalaz.resize(400, 300)
        self.rtgIzlaz = QtWidgets.QPushButton(RTGNalaz)
        self.rtgIzlaz.setGeometry(QtCore.QRect(320, 270, 75, 23))
        self.rtgIzlaz.setObjectName("rtgIzlaz")
        self.rtgDialogText = QtWidgets.QPlainTextEdit(RTGNalaz)
        self.rtgDialogText.setGeometry(QtCore.QRect(10, 20, 381, 251))
        self.rtgDialogText.setObjectName("rtgDialogText")
        self.label_2 = QtWidgets.QLabel(RTGNalaz)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.rtgOKButton = QtWidgets.QPushButton(RTGNalaz)
        self.rtgOKButton.setGeometry(QtCore.QRect(160, 270, 75, 23))
        self.rtgOKButton.setObjectName("rtgOKButton")

        self.retranslateUi(RTGNalaz)
        QtCore.QMetaObject.connectSlotsByName(RTGNalaz)
        self.rtgOKButton.clicked.connect(self.getText)
        self.rtgIzlaz.clicked.connect(RTGNalaz.close)


    def retranslateUi(self, RTGNalaz):
        _translate = QtCore.QCoreApplication.translate
        RTGNalaz.setWindowTitle(_translate("RTGNalaz", "RTG Nalaz"))
        self.rtgIzlaz.setText(_translate("RTGNalaz", "Izlaz!"))
        self.label_2.setText(_translate("RTGNalaz", "Opis dati ovde!"))
        self.rtgOKButton.setText(_translate("RTGNalaz", "OK"))
    def getText(self):
        self.rtg_Nalaz = self.rtgDialogText.toPlainText()
        self.rtgOKButton.setEnabled(False)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RTGNalaz = QtWidgets.QDialog()
    ui = Ui_RTGNalaz()
    ui.setupUi(RTGNalaz)
    RTGNalaz.show()
    sys.exit(app.exec_())
